version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus-conf:/etc/prometheus
      - prometheus-data:/prometheus
    restart: always
    tty: true

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    restart: always
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: 'true'
      GF_INSTALL_PLUGINS: 'grafana-clock-panel'

  influxdb:
    image: influxdb:1.4
    ports:
      - 8086:8086
      - '8888:8888/udp' # For UDP, Arduino
    volumes:
      - influxdb-data:/var/lib/influxdb
      - influxdb-conf:/etc/influxdb
    tty: true
    restart: always
    environment:
      INFLUXDB_DB: ${INFLUXDB_DB}
      INFLUXDB_HTTP_AUTH_ENABLED: 'false'
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      INFLUXDB_USER: ${INFLUXDB_USER}
      INFLUXDB_USER_PASSWORD: ${INFLUXDB_USER_PASSWORD}
      INFLUXDB_READ_USER: ${INFLUXDB_READ_USER}
      INFLUXDB_READ_USER_PASSWORD: ${INFLUXDB_READ_USER_PASSWORD}

volumes:
  influxdb-data:
  influxdb-conf:
  prometheus-conf:
  prometheus-data:
  grafana: 
